# --------------------------------------------------------------------------- #
# general configuration
# --------------------------------------------------------------------------- #
version: 1.4.0.{build}
branches:
  except:
    - net35
skip_tags: true

# --------------------------------------------------------------------------- #
# environment configuration
# --------------------------------------------------------------------------- #
clone_folder: C:\Cube\Cube.Net
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true

# --------------------------------------------------------------------------- #
# build configuration
# --------------------------------------------------------------------------- #
platform: Any CPU
configuration: Release
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget restore Cube.Net.sln
build: 
  parallel: true
  project: Cube.Net.sln
  publish_nuget: true
  verbosity: normal

# --------------------------------------------------------------------------- #
# tests configuration
# --------------------------------------------------------------------------- #
test_script:
    - ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"Cube.Net.Tests.dll" -targetdir:".\Tests\bin\Release" -hideskipped:All -output:CoverResult.xml
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "CoverResult.xml"
    