version: 1.10.0.{build}
branches:
    only:
        - chrome
skip_tags: true
clone_folder: C:\Cube\Cube.Net
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform:
    - x86
    - x64
configuration: Release
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - nuget sources add -name Cube.Xui -source https://ci.appveyor.com/nuget/cube.xui
    - nuget restore Cube.Net.Rss.sln
build:
    parallel: true
    project: Cube.Net.Rss.sln
    publish_nuget: true
    verbosity: minimal
test:
    assemblies:
        only:
            - Cube.Net.Rss.Tests.dll
artifacts:
    - path: Applications\Rss\Reader\bin\x86\Release
      name: CubeRssReader.Chrome.x86
    - path: Applications\Rss\Reader\bin\x64\Release
      name: CubeRssReader.Chrome.x64
